let d3Demo = () => window.location.href = "../demo/d3.js_demo/d3.html"
let d3Experiment = () => window.location.href = "../random_generation/random_d3/random_d3.html"
let cytoDemo = () => window.location.href = "../demo/cytoscape.js_demo/cytoscape.html"
let cytoExperiment = () => window.location.href = "../random_generation/random_cytoscape/random_cytoscape.html"
let visDemo = () => window.location.href = "../demo/vis.js_demo/vis.html"
let visExperiment = () => window.location.href = "../random_generation/random_vis/random_vis.html"
